- hosts: localhost
  gather_facts: false
  vars:
    ansible_connection: local
    # This variable will be coming from jenkins as extra vars
    databases: "{{ migration_databses.split(',') }}"
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  roles:
    - postgres-migration
